name: flutter_dino_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  form_field_validator: ^1.1.0

  cupertino_icons: ^1.0.2
  sqflite: ^2.1.0+1
  path: ^1.8.2
  equatable: ^2.0.5
  flutter_riverpod: 2.0.2
  sleek_circular_slider: ^2.0.1
  rive: ^0.9.0
  supabase_flutter: ^1.2.2
  pocketbase: ^0.7.0
  oauth2: ^2.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  import_sorter: ^4.6.0
  dependency_validator: ^3.2.0

  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.19.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/rive/
